### ISSUE TITLE
Attempting to run git commands in ./addons when no .git directory exists

### ISSUE THREAD

**Issue by Renari** [chickensoft-games/GodotEnv#60]
```
// Godot addons configuration file for use with the GodotEnv tool.
// See https://github.com/chickensoft-games/GodotEnv for more info.
// -------------------------------------------------------------------- //
// Note: this is a JSONC file, so you can use comments!
// If using Rider, see https://youtrack.jetbrains.com/issue/RIDER-41716
// for any issues with JSONC.
// -------------------------------------------------------------------- //
{
  "$schema": "https://chickensoft.games/schemas/addons.schema.json",
  // "path": "addons", // default
  // "cache": ".addons", // default
  "addons": {
    "imrp": { // name must match the folder name in the repository
      "url": "https://github.com/MakovWait/improved_resource_picker",
      // "source": "remote", // default
      // "checkout": "main", // default
      "subfolder": "addons/imrp"
    }
  }
}
```
The default `addons.jsonc` file shown above seems to be trying to run `git config --local user.email godotenv@godotenv.com` in `./addons/imrp/` after moving the the `./.addons/imrp/addons/imrp/` directory to this location. Since this isn't moving over the whole repo and is instead moving a subfolder, this command fails because it is no longer a git repo.

Relevant output:
```
$ godotenv.exe addons install
Discovered "imrp."

  Resolved: Addon "imrp" from `addons.jsonc` at `addons/imrp/` on branch `main` of `https://github.com/MakovWait/improved_resource_picker`

An error was encountered while attempting to install addons.

System.InvalidOperationException: Failed to run `git` in `V:\godot-game\addons\imrp\` with args `config --local user.email godotenv@godotenv.com`. Received exit code 128.
   at Chickensoft.GodotEnv.Common.Utilities.Shell.Run(String executable, String[] args) in /home/runner/work/GodotEnv/GodotEnv/GodotEnv/src/common/utilities/Shell.cs:line 29
   at Chickensoft.GodotEnv.Features.Addons.Domain.AddonsRepository.InstallAddonFromCache(IAddon addon, String cacheName) in /home/runner/work/GodotEnv/GodotEnv/GodotEnv/src/features/addons/domain/AddonsRepository.cs:line 220
   at Chickensoft.GodotEnv.Features.Addons.Commands.AddonsLogic.State.Unresolved.On(Install input) in /home/runner/work/GodotEnv/GodotEnv/GodotEnv/src/features/addons/commands/install/AddonsLogic.cs:line 141
   at Chickensoft.LogicBlocks.LogicBlockAsync`1.RunSafe(Func`1 handler, TState fallback)

An error occurred while installing addons:
Failed to run `git` in `V:\godot-game\addons\imrp\` with args `config --local user.email godotenv@godotenv.com`. Received exit code 128.

Could not resolve addons. Please address any errors and try again.
```

**Comment by Renari** [comment]
After doing a little digging it seems this is irrelevant to the above error. https://github.com/chickensoft-games/GodotEnv/blob/794641b442eb7336c4f3d631b7dcc12fbae2c806/GodotEnv/src/features/addons/domain/AddonsRepository.cs#L224

Is initializing a git repo in this location, when attempting to perform these steps manually I encountered the error:
```
$ git config --local user.email godotenv@godotenv.com
fatal: --local can only be used inside a git repository
$ git status
fatal: detected dubious ownership in repository at '//TRUENAS/dev/godot-game/addons/imrp'
'//TRUENAS/dev/godot-game/addons/imrp' is on a file system that does not record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory '%(prefix)///TRUENAS/dev/godot-game/addons/imrp'
```
Running the above recommended command, removing `./.addons/imrp` and `./addons/imrp`, and rerunning `godotenv addons install` the process went through successfully.

**Comment by Renari** [comment]
It seems this is related to this CVE:

https://github.blog/2022-04-12-git-security-vulnerability-announced/

Since I'm not using a shared system, this CVE isn't that relevant to me so it's somewhat safe to just whitelist all directories.
