### ISSUE TITLE
`godotenv godot list` throws NullReferenceException

### ISSUE THREAD

**Issue by xill47** [chickensoft-games/GodotEnv#68]
Regular `godotenv godot list` (which I would expect to list locally installed managed versions) throws 

```
System.NullReferenceException: Object reference not set to an instance of an object.
  at Chickensoft.GodotEnv.Features.Godot.Domain.GodotRepository.<>c.<GetInstallationsList>b__48_0(GodotInstallation i) in \home\runner\work\GodotEnv\GodotEnv\GodotEnv\src\features\godot\domain\GodotRepository.cs:595
  at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
  at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
  at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
  at System.Linq.OrderedEnumerable`1.ToList()
  at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
  at Chickensoft.GodotEnv.Features.Godot.Domain.GodotRepository.GetInstallationsList() in \home\runner\work\GodotEnv\GodotEnv\GodotEnv\src\features\godot\domain\GodotRepository.cs:567
  at Chickensoft.GodotEnv.Features.Addons.Commands.GodotListCommand.ListLocalVersions(ILog log, IGodotRepository godotRepo) in \home\runner\work\GodotEnv\GodotEnv\GodotEnv\src\features\godot\commands\GodotListCommand.cs:25
  at Chickensoft.GodotEnv.Features.Addons.Commands.GodotListCommand.ExecuteAsync(IConsole console) in \home\runner\work\GodotEnv\GodotEnv\GodotEnv\src\features\godot\commands\GodotListCommand.cs:53
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in \_\CliFx\CliApplication.cs:153
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in \_\CliFx\CliApplication.cs:193
```

**Comment by xill47** [comment]
```
Folder PATH listing
Volume serial number is D439-B815
C:.
+---godot_dotnet_3_5_2
|   \---Godot_v3.5.2-stable_mono_win64
|       \---GodotSharp
|           +---Api
|           |   +---Debug
|           |   \---Release
|           +---Mono
|           |   +---bin
|           |   +---etc
|           |   |   \---mono
|           |   |       +---2.0
|           |   |       |   \---Browsers
|           |   |       +---4.0
|           |   |       |   \---Browsers
|           |   |       \---4.5
|           |   |           \---Browsers
|           |   \---lib
|           |       \---mono
|           |           +---4.5
|           |           |   \---Facades
|           |           \---v4.0
|           \---Tools
|               \---aot-compilers
|                   \---iphone-arm64
+---godot_dotnet_3_5_3
|   \---Godot_v3.5.3-stable_mono_win64
|       \---GodotSharp
|           +---Api
|           |   +---Debug
|           |   \---Release
|           +---Mono
|           |   +---bin
|           |   +---etc
|           |   |   \---mono
|           |   |       +---2.0
|           |   |       |   \---Browsers
|           |   |       +---4.0
|           |   |       |   \---Browsers
|           |   |       \---4.5
|           |   |           \---Browsers
|           |   \---lib
|           |       \---mono
|           |           +---4.5
|           |           |   \---Facades
|           |           \---v4.0
|           \---Tools
|               \---aot-compilers
|                   \---iphone-arm64
+---godot_dotnet_4_2_0
|   \---Godot_v4.2-stable_mono_win64
|       \---GodotSharp
|           +---Api
|           |   +---Debug
|           |   \---Release
|           \---Tools
|               \---nupkgs
+---godot_dotnet_4_2_2
|   \---Godot_v4.2.2-stable_mono_win64
|       \---GodotSharp
|           +---Api
|           |   +---Debug
|           |   \---Release
|           \---Tools
|               \---nupkgs
+---godot_dotnet_4_3_0_beta1
|   \---Godot_v4.3-beta1_mono_win64
|       \---GodotSharp
|           +---Api
|           |   +---Debug
|           |   \---Release
|           \---Tools
|               \---nupkgs
\---godot_dotnet_4_3_0_beta_2
    \---Godot_v4.3-beta2_mono_win64
        \---GodotSharp
            +---Api
            |   +---Debug
            |   \---Release
            \---Tools
                \---nupkgs
```

**Comment by xill47** [comment]
Seems to fail on versionString 4.3.0 when parsing beta1

**Comment by xill47** [comment]
I see, `godotenv godot install 4.3.0-beta1` installs into `Godot_v4.3-beta1_mono_win64` while `godotenv godot install 4.3.0-beta.1` installs correctly

**Comment by xill47** [comment]
I might take a closer look into it tomorrow, maybe will create a fix

**Comment by InfiniteCanvas** [comment]
Had the same error, fixed by adjusting the regex so it matches the label.
```csharp
  public static readonly Regex DirectoryToVersionStringRegex = new(
    @"godot_(dotnet_)?(?<major>\d+)_(?<minor>\d+)_(?<patch>\d+)_?(?<label>[a-zA-Z]+_?[\d]+)?",
    RegexOptions.Compiled | RegexOptions.IgnoreCase
  );
```
It's just the ? after the _ in the label capture group.

**Comment by xill47** [comment]
Should directories that failed to parse also be skipped in enumeration? Either that, or printed as plain text / error message? NRE is pretty bad Dx

**Comment by InfiniteCanvas** [comment]
Godot dudes seem to label their stuff one way today, another way tomorrow lol
It just expands it to match "beta_1" and allow "beta1," which seems to be the two schemes they use. I think it works out fine enough. 
But maybe you're right and the "make it work first, think about smart solution later" is not always a good approach lmao
