### ISSUE TITLE
godotenv godot list doesn't work if you run a single installation with the -stable suffix

### ISSUE THREAD

**Issue by DarkPro1337** [chickensoft-games/GodotEnv#89]
I tried to install Godot 4.3.0 stable via `godotenv godot install 4.0.1-stable` since `godotenv godot list -r` outputs versions with suffixes. After successful installation, `godotenv godot list` returns an `NullReferenceException` to output:
```
PS C:\Users\admin> godotenv godot list
ERROR
System.NullReferenceException: Object reference not set to an instance of an object.
  at Chickensoft.GodotEnv.Features.Godot.Domain.GodotRepository.<>c.<GetInstallationsList>b__48_0(GodotInstallation i) in \home\runner\work\GodotEnv\GodotEnv\GodotEnv\src\features\godot\domain\GodotRepository.cs:578
  at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
  at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
  at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
  at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
  at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
  at Chickensoft.GodotEnv.Features.Godot.Domain.GodotRepository.GetInstallationsList() in \home\runner\work\GodotEnv\GodotEnv\GodotEnv\src\features\godot\domain\GodotRepository.cs:578
  at Chickensoft.GodotEnv.Features.Addons.Commands.GodotListCommand.ListLocalVersions(ILog log, IGodotRepository godotRepo) in \home\runner\work\GodotEnv\GodotEnv\GodotEnv\src\features\godot\commands\GodotListCommand.cs:25
  at Chickensoft.GodotEnv.Features.Addons.Commands.GodotListCommand.ExecuteAsync(IConsole console) in \home\runner\work\GodotEnv\GodotEnv\GodotEnv\src\features\godot\commands\GodotListCommand.cs:53
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in \_\CliFx\CliApplication.cs:163
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in \_\CliFx\CliApplication.cs:204
```

After I tried installing 4.3.0 just without the suffix `godotenv godot install 4.3.0`, the `godotenv godot list` command worked, but started outputting two identical versions.
```
PS C:\Users\admin> godotenv godot list
4.3.0 dotnet *
4.3.0 dotnet *
```

Seems to be a bug due to the `-stable` suffix introduced for the version. I hope this repro will help to find the bug. This was a fresh installation of GodotEnv.

**Comment by DarkPro1337** [comment]
> What do you mean by you were you installing `4.3.0` with `4.0.1-stable`? Those are two totally different versions.

I'm sorry I made a mistake in my sentence. I was installing `4.3.0-stable` and `4.3.0`. :|

**Comment by AdriaandeJongh** [comment]
also ran into this! may I suggest allowing the list command to at least work / not give a nullref when the user has followed the readme to the letter? 😏  because the readme mentions `godotenv godot install 4.0.1` and not `godotenv godot install 4.0.1-stable`
